# Generated by Django 5.1.6 on 2025-02-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emial',
            new_name='email',
        ),
    ]
